server:
  port: 9999
  tomcat:
    uri-encoding: utf-8
spring:
  application:
    name: activity_demo
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/activity
    username: root
    password: developer
  activiti:
    check-process-definitions: true
